"""Convert ParsedFile → WireMock JSON mapping files packaged as a ZIP.

Called at upload time so the WireMock ZIP is ready before the user clicks
Generate.  The generate job endpoint reads this ZIP back from local storage
and returns it to the portal; no SQS / worker needed for local dev.

Mapping construction itself is delegated entirely to
parser_worker.generator.wiremock.build_wiremock_mappings — this used to have
its own independent, simpler mapping builder that had no bodyPatterns
support at all, so any stub with more than one scenario at the same URL
(the same-URL-differentiation case this whole generator exists for) would
produce mapping files that collide in WireMock with no way to disambiguate
between them. Delegating means this ZIP can never drift from what the full
Spring Boot project (stub-engine.zip) actually serves.
"""
from __future__ import annotations

import io
import json
import re
import zipfile

from parser_worker.generator.wiremock import build_wiremock_mappings
from parser_worker.models import ParsedFile


def _sanitise(name: str) -> str:
    """Make a filename-safe slug from an arbitrary string."""
    slug = re.sub(r"[^\w\-]", "_", name).strip("_")
    return slug[:80] or "stub"


def generate_wiremock_zip(parsed_file: ParsedFile) -> bytes:
    """Return a ZIP archive containing all WireMock mapping JSON files.

    Layout inside the ZIP:
        mappings/
            <stub_slug>/
                <scenario_slug>.json

    include_lookup_table_stubs=True: this ZIP is just raw JSON mapping files
    with no accompanying Java code, so a stub that would otherwise get the
    dynamic lookup-table treatment (see generator/lookup_table.py) still
    needs its static per-scenario mappings here — there's no
    DynamicLookupRequestFilter to hand it off to in a plain "drop these
    files into WireMock" download.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for stub, scenario, mapping in build_wiremock_mappings(parsed_file, include_lookup_table_stubs=True):
            filename = f"mappings/{_sanitise(stub.name)}/{_sanitise(scenario.name)}.json"
            zf.writestr(filename, json.dumps(mapping, indent=2))

        # README inside the ZIP
        readme = (
            "# WireMock Mappings — generated by Mockingbird\n\n"
            "Drop the `mappings/` folder into your WireMock server's root directory,\n"
            "or mount it into the Spring Boot stub container.\n\n"
            f"Source format : {parsed_file.format}\n"
            f"Source file   : {parsed_file.source_file}\n"
            f"Stubs         : {len(parsed_file.stubs)}\n"
            f"Scenarios     : {sum(len(s.scenarios) for s in parsed_file.stubs)}\n"
        )
        zf.writestr("README.md", readme)

    return buf.getvalue()
