"""PDF report renderer using WeasyPrint.

Generates a branded HTML page then converts it to PDF bytes via WeasyPrint.
The HTML template is inline (no external file dependency) so the renderer
works inside a Docker container with no filesystem write access.
"""
from __future__ import annotations

from ..models import ReportData

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  @page {{ size: A4; margin: 20mm; }}
  body {{ font-family: Arial, sans-serif; color: #222; }}
  .header {{ background: {primary}; color: white; padding: 16px 20px; }}
  .header h1 {{ margin: 0; font-size: 22px; }}
  .header p  {{ margin: 4px 0 0; font-size: 12px; opacity: 0.85; }}
  .section   {{ margin: 20px 0; }}
  h2         {{ color: {primary}; border-bottom: 2px solid {secondary}; padding-bottom: 4px; }}
  table      {{ border-collapse: collapse; width: 100%; font-size: 13px; }}
  th         {{ background: {secondary}; color: white; padding: 8px; text-align: left; }}
  td         {{ padding: 7px 8px; border-bottom: 1px solid #ddd; }}
  tr:nth-child(even) td {{ background: #f5f8fc; }}
  .kpi       {{ display: inline-block; width: 22%; margin: 0 1%; padding: 12px;
               background: {primary}; color: white; border-radius: 4px; text-align: center; }}
  .kpi .val  {{ font-size: 28px; font-weight: bold; }}
  .kpi .lbl  {{ font-size: 11px; opacity: 0.85; }}
  .footer    {{ font-size: 10px; color: #999; text-align: center; margin-top: 30px; }}
</style>
</head>
<body>
<div class="header">
  <h1>{company} — Stub Engine Performance Report</h1>
  <p>Project: {project_name} | Stub: {stub_name} | Generated: {generated_at}</p>
</div>

<div class="section">
  <h2>Summary</h2>
  <div>
    <div class="kpi"><div class="val">{peak_tps:,.0f}</div><div class="lbl">Peak TPS</div></div>
    <div class="kpi"><div class="val">{avg_tps:,.0f}</div><div class="lbl">Avg TPS</div></div>
    <div class="kpi"><div class="val">{avg_latency_ms:.1f}ms</div><div class="lbl">Avg Latency</div></div>
    <div class="kpi"><div class="val">{error_rate_pct:.2f}%</div><div class="lbl">Error Rate</div></div>
  </div>
</div>

<div class="section">
  <h2>Configuration</h2>
  <table>
    <tr><th>Parameter</th><th>Value</th></tr>
    <tr><td>Environment</td><td>{environment}</td></tr>
    <tr><td>Stub URL</td><td>{stub_url}</td></tr>
    <tr><td>Report Period</td><td>Last {report_period_hours} hours</td></tr>
    <tr><td>Total Requests</td><td>{total_requests:,}</td></tr>
    <tr><td>p95 Latency</td><td>{p95_latency_ms:.1f} ms</td></tr>
  </table>
</div>

<div class="section">
  <h2>Time Series (last {point_count} observations)</h2>
  <table>
    <tr><th>Time (UTC)</th><th>TPS</th><th>Avg Latency (ms)</th><th>Error Rate (%)</th></tr>
    {rows}
  </table>
</div>

<div class="footer">
  Generated by Mockingbird SV Platform &mdash; {company}
</div>
</body>
</html>
"""

_ROW_TEMPLATE = (
    "<tr><td>{time}</td><td>{tps:,.1f}</td>"
    "<td>{latency:.2f}</td><td>{err:.4f}</td></tr>"
)


def render_html(data: ReportData, primary: str, secondary: str, company: str) -> str:
    """Render the report as an HTML string (used for both PDF and testing)."""
    rows = "\n".join(
        _ROW_TEMPLATE.format(
            time=p.time.strftime("%Y-%m-%d %H:%M"),
            tps=p.tps,
            latency=p.latency_avg_ms,
            err=p.error_rate * 100,
        )
        for p in data.points
    )
    return _HTML_TEMPLATE.format(
        primary=primary,
        secondary=secondary,
        company=company,
        project_name=data.project_name,
        stub_name=data.stub_name,
        generated_at=data.generated_at.strftime("%Y-%m-%d %H:%M UTC"),
        peak_tps=data.peak_tps,
        avg_tps=data.avg_tps,
        avg_latency_ms=data.avg_latency_ms,
        error_rate_pct=data.error_rate_pct,
        environment=data.environment,
        stub_url=data.stub_url,
        report_period_hours=data.report_period_hours,
        total_requests=data.total_requests,
        p95_latency_ms=data.p95_latency_ms,
        point_count=len(data.points),
        rows=rows,
    )


def render_pdf(data: ReportData, primary: str, secondary: str, company: str) -> bytes:
    """Render a branded A4 PDF. Returns raw bytes."""
    from weasyprint import HTML  # imported lazily — not available in test env

    html = render_html(data, primary, secondary, company)
    return HTML(string=html).write_pdf()
