"""Generates Microcks deployment config from a ParsedAsyncApiFile (Sprint 23).

Output directory structure:
    output/
    ├── docker-compose.microcks.yml   — runs Microcks uber image
    ├── asyncapi.yaml                 — the spec file Microcks reads
    └── .env.microcks                 — env var template for the operator

Microcks uber image bundles everything (app + MongoDB + async minion).
It is pulled from the Artifactory Docker mirror at runtime — no build step needed.
The deployer-worker SSH-copies these files to the EC2 and runs docker-compose up.
"""
from __future__ import annotations

from pathlib import Path

from ..models_asyncapi import ParsedAsyncApiFile

_COMPOSE_TEMPLATE = """\
# Auto-generated by Mockingbird — do not edit manually
# Project: {project_name} ({project_id})
# Engine:  Microcks (AsyncAPI + Avro)
services:
  microcks:
    image: ${{MICROCKS_IMAGE:-quay.io/microcks/microcks-uber:latest}}
    container_name: microcks-{project_id}
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=uber
      - ASYNC_PROTOCOLS=KAFKA
      - KAFKA_BOOTSTRAP_SERVER=${{KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}}
      - SCHEMA_REGISTRY_URL=${{SCHEMA_REGISTRY_URL:-}}
      - MICROCKS_GRPC_HOST=localhost
      - MICROCKS_GRPC_PORT=9090
      - STUB_PROJECT_ID={project_id}
      - STUB_PROJECT_NAME={project_name}
    volumes:
      - ./asyncapi.yaml:/opt/microcks/data/asyncapi.yaml
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
"""

_ENV_TEMPLATE = """\
# Microcks environment — fill in before deploying
# Project: {project_name} ({project_id})

# Kafka broker (required for AsyncAPI channel mocking)
KAFKA_BOOTSTRAP_SERVERS=localhost:9092

# Avro schema registry URL (leave blank if no Avro schemas)
SCHEMA_REGISTRY_URL=

# Microcks Docker image (from Artifactory mirror)
MICROCKS_IMAGE=quay.io/microcks/microcks-uber:latest
"""


def generate_microcks_config(
    parsed: ParsedAsyncApiFile,
    raw_spec: str,
    output_dir: Path,
    project_id: str = "",
    project_name: str = "",
) -> Path:
    """Write Microcks deployment config to output_dir.

    Args:
        parsed:      Parsed AsyncAPI spec.
        raw_spec:    Raw spec content (YAML or JSON string) — written as asyncapi.yaml.
        output_dir:  Target directory; created if absent.
        project_id:  Short identifier used as container name suffix.
        project_name: Human-readable project name.

    Returns:
        output_dir.
    """
    if not project_id:
        project_id = _to_id(parsed.title or "asyncapi-stub")
    if not project_name:
        project_name = parsed.title or "AsyncAPI Stub"

    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. docker-compose.microcks.yml
    compose_content = _COMPOSE_TEMPLATE.format(
        project_id=project_id,
        project_name=project_name,
    )
    (output_dir / "docker-compose.microcks.yml").write_text(compose_content, encoding="utf-8")

    # 2. asyncapi.yaml — the spec Microcks reads from the mounted volume
    (output_dir / "asyncapi.yaml").write_text(raw_spec, encoding="utf-8")

    # 3. .env.microcks — operator fills in before deploy
    env_content = _ENV_TEMPLATE.format(project_id=project_id, project_name=project_name)
    (output_dir / ".env.microcks").write_text(env_content, encoding="utf-8")

    return output_dir


def _to_id(name: str) -> str:
    import re
    return re.sub(r"[^\w-]", "-", name.lower()).strip("-")[:50]
